---

language: ruby
cache: bundler
env:
        GEM="sudo gem"
os:
        - linux
        - osx
#rvm:
#        - system

#jobs:
#        include:
#                - rvm: 2.5.3
#                  os: linux
#                  env: GEM=gem

before_install:
        - rvm use system
        - echo ${GEM}
        - ${GEM} update --system
        - ${GEM} install bundler

script: bundle exec rspec
